### ISSUE TITLE
Not for DSO138

### ISSUE THREAD

**Issue by gschwaer** [Depau/dso138-viewer#1]
I wanted to try this project with my DSO138, but I cannot find a way to send the waveform.

> If your scope is connected, hold the SEL button to send the data and view it.

Long pressing SEL only cycles through the menu items. I think this is expected, since JYE Tech [does not list this feature for the DSO138](https://jyetech.com/dso-138-oscilloscope-diy-kit/). For the [DSO138mini they do state this is possible](https://jyetech.com/dso138mini-oscilloscope-diy-kit/).

**Comment by depau** [comment]
You're right, it's for the DSO138mini. Sorry for the confusion.
